from __future__ import annotations

from pathlib import Path
from typing import Type

from agents import Agent, Model, function_tool
from agents.sandbox import Manifest, SandboxAgent, SandboxPathGrant
from agents.sandbox.capabilities import Capabilities, LocalDirLazySkillSource, Skills
from agents.sandbox.entries import LocalDir
from pydantic import BaseModel

SKILLS_DIR = Path(__file__).resolve().parents[2] / "skills"

GUIDELINE_SEARCHER_INSTRUCTIONS = """
You are a Guideline Searcher Agent for gastroenterology diagnosis.

You will receive the search_queries generated by the Gastroenterology Search Planning Agent
and local disease guideline skills. Extract guideline evidence relevant to differential diagnosis,
diagnostic criteria, confirmation tests, and recommended next steps.

For every guideline_evidence item, identify the exact loaded skill that supports the evidence and
format the item as:
skill name：guideline evidence
Preserve the original local skill name, use the full-width Chinese colon "：" as the separator, and
do not add quotation marks around either part. If evidence comes from different skills, output it as
separate items with the corresponding skill name. Do not combine evidence from multiple skills into
one item.

If the skill materials do not provide clear evidence, do not invent recommendation numbers,
evidence levels, recommendation strengths, or guideline statements.

Keep skill_names as the original local skill identifiers.
Return only used_skill, skill_names, and guideline_evidence in the structured output.
""".strip()

SANDBOX_SKILL_INSTRUCTIONS = """
Use the sandbox Skills capability:
1. Inspect the available skills.
2. Call load_skill for a relevant disease guideline skill.
3. Read .agents/{skill_name}/SKILL.md and follow its workflow to read references or run scripts.
""".strip()

FUNCTION_TOOL_SKILL_INSTRUCTIONS = """
Use the local guideline function tools:
1. Call list_guideline_skills to inspect the available guideline skills.
2. Call read_guideline_file with file_name "SKILL.md" for a relevant skill and follow its workflow.
3. Search "recommendations-index.md" first with search_guideline.
4. Read the corresponding lines from "guideline-full-text.md" with read_guideline_file to verify
   the original context. Search the full text directly when the index has no clear match.
""".strip()

GUIDELINE_FILES = {
    "SKILL.md": "SKILL.md",
    "recommendations-index.md": "references/recommendations-index.md",
    "guideline-full-text.md": "references/guideline-full-text.md",
    "guideline-page-map.json": "references/guideline-page-map.json",
}


def _resolve_guideline_skill(skill_name: str) -> Path:
    skills = {
        path.name: path
        for path in SKILLS_DIR.iterdir()
        if path.is_dir() and (path / "SKILL.md").is_file()
    }
    if skill_name not in skills:
        raise ValueError(f"Unknown guideline skill: {skill_name}")
    return skills[skill_name]


@function_tool
def list_guideline_skills() -> list[dict[str, str]]:
    """List available local guideline skills with their descriptions."""
    skills: list[dict[str, str]] = []
    for path in sorted(SKILLS_DIR.iterdir(), key=lambda item: item.name):
        skill_md = path / "SKILL.md"
        if not path.is_dir() or not skill_md.is_file():
            continue
        description = ""
        for line in skill_md.read_text(encoding="utf-8").splitlines():
            if line.startswith("description:"):
                description = line.split(":", 1)[1].strip().strip("\"'")
                break
        skills.append({"name": path.name, "description": description})
    return skills


@function_tool
def search_guideline(
    skill_name: str,
    keywords: list[str],
    file_name: str = "recommendations-index.md",
    context_lines: int = 2,
) -> str:
    """Search all keywords in one allowed guideline reference file and return numbered context lines."""
    if file_name not in {"recommendations-index.md", "guideline-full-text.md"}:
        raise ValueError(f"Unsupported guideline search file: {file_name}")
    target = _resolve_guideline_skill(skill_name) / GUIDELINE_FILES[file_name]
    lines = target.read_text(encoding="utf-8").splitlines()
    normalized_keywords = [keyword.casefold() for keyword in keywords]
    hit_lines: set[int] = set()
    for index, line in enumerate(lines):
        normalized_line = line.casefold()
        if all(keyword in normalized_line for keyword in normalized_keywords):
            start = max(0, index - context_lines)
            end = min(len(lines), index + context_lines + 1)
            hit_lines.update(range(start, end))
    if not hit_lines:
        return "No matching guideline content found."
    output: list[str] = []
    previous = -2
    for index in sorted(hit_lines):
        if index != previous + 1:
            output.append("---")
        output.append(f"{index + 1}: {lines[index]}")
        previous = index
    return "\n".join(output)


@function_tool
def read_guideline_file(
    skill_name: str,
    file_name: str,
    start_line: int = 1,
    end_line: int = 200,
) -> str:
    """Read a numbered line range from one allowed file in a local guideline skill."""
    if file_name not in GUIDELINE_FILES:
        raise ValueError(f"Unsupported guideline file: {file_name}")
    target = _resolve_guideline_skill(skill_name) / GUIDELINE_FILES[file_name]
    lines = target.read_text(encoding="utf-8").splitlines()
    start = max(1, start_line)
    end = min(len(lines), end_line)
    return "\n".join(
        f"{index}: {lines[index - 1]}"
        for index in range(start, end + 1)
    )


def _build_guideline_skill_capability() -> Skills:
    return Skills(
        lazy_from=LocalDirLazySkillSource(
            source=LocalDir(src=SKILLS_DIR),
        ),
    )


def _build_guideline_skill_manifest() -> Manifest:
    return Manifest(
        extra_path_grants=(
            SandboxPathGrant(
                path=str(SKILLS_DIR),
                read_only=True,
                description="Disease guideline skill source directory",
            ),
        ),
    )


def build_guideline_searcher_agent(
    output_type: Type[BaseModel],
    model: str | Model,
    *,
    native_structured_output: bool = True,
) -> Agent | SandboxAgent:
    if native_structured_output:
        return SandboxAgent(
            name="Guideline Searcher Agent",
            model=model,
            instructions=f"{GUIDELINE_SEARCHER_INSTRUCTIONS}\n\n{SANDBOX_SKILL_INSTRUCTIONS}",
            output_type=output_type,
            capabilities=[
                *Capabilities.default(),
                _build_guideline_skill_capability(),
            ],
            default_manifest=_build_guideline_skill_manifest(),
        )
    return Agent(
        name="Guideline Searcher Agent",
        model=model,
        instructions=f"{GUIDELINE_SEARCHER_INSTRUCTIONS}\n\n{FUNCTION_TOOL_SKILL_INSTRUCTIONS}",
        tools=[list_guideline_skills, search_guideline, read_guideline_file],
    )
