from __future__ import annotations

import json
import random
import threading
import time
import urllib.error
import urllib.parse
import urllib.request
from collections.abc import Iterator
from concurrent.futures import ThreadPoolExecutor
from typing import Any

from agents import Agent, Model
from langchain_community.retrievers import PubMedRetriever

from config import (
    NCBI_API_KEY,
    NCBI_EMAIL,
    NCBI_MAX_RETRIES,
    NCBI_REQUESTS_PER_SECOND,
    NCBI_RETRY_BASE_SECONDS,
    NCBI_TIMEOUT_SECONDS,
    NCBI_TOOL,
)
from schemas import KnowledgeSearchSelectionResult


KNOWLEDGE_SEARCHER_INSTRUCTIONS = """
You are a clinical Knowledge search specialist in gastroenterology.

Task:
1. Read the provided search_queries generated by the Gastroenterology Search Planning Agent.
2. Review the provided PubMed search results.
3. Select the PMIDs of results whose title and abstract are relevant to one or more provided search queries.
4. A PMID retrieved by multiple search queries should receive additional consideration because repeated
   retrieval is a relevance signal, but repetition alone is not sufficient when the publication content
   is unrelated to the queries.
5. Return each selected PMID only once, in the order of its first appearance in the provided results.
6. Copy selected numeric PMIDs exactly from the provided results. Do not invent or modify PMIDs.
7. Output only selected_pmids. Do not output, copy, rewrite, summarize, or quote any query, title,
   abstract, URL, evidence, explanation, or unselected PubMed result.
""".strip()


class _NcbiRateLimiter:
    def __init__(self, requests_per_second: float) -> None:
        self._minimum_interval = 1.0 / max(requests_per_second, 0.1)
        self._lock = threading.Lock()
        self._last_request_at = 0.0

    def wait(self) -> None:
        with self._lock:
            now = time.monotonic()
            wait_seconds = self._minimum_interval - (now - self._last_request_at)
            if wait_seconds > 0:
                time.sleep(wait_seconds)
            self._last_request_at = time.monotonic()


_NCBI_RATE_LIMITER = _NcbiRateLimiter(NCBI_REQUESTS_PER_SECOND)


def _request_ncbi(url: str) -> bytes:
    for retry_index in range(NCBI_MAX_RETRIES + 1):
        _NCBI_RATE_LIMITER.wait()
        try:
            with urllib.request.urlopen(url, timeout=NCBI_TIMEOUT_SECONDS) as response:
                return response.read()
        except urllib.error.HTTPError as exc:
            retryable = exc.code == 429 or 500 <= exc.code < 600
            if not retryable or retry_index >= NCBI_MAX_RETRIES:
                raise
            retry_after = exc.headers.get("Retry-After")
            try:
                retry_after_seconds = float(retry_after) if retry_after else 0.0
            except ValueError:
                retry_after_seconds = 0.0
        except urllib.error.URLError:
            if retry_index >= NCBI_MAX_RETRIES:
                raise
            retry_after_seconds = 0.0

        exponential_delay = NCBI_RETRY_BASE_SECONDS * (2**retry_index)
        jitter = random.uniform(0, NCBI_RETRY_BASE_SECONDS)
        time.sleep(max(retry_after_seconds, exponential_delay + jitter))

    raise RuntimeError("NCBI request retry loop exited unexpectedly")


def _ncbi_url(base_url: str, parameters: dict[str, str]) -> str:
    request_parameters = {
        **parameters,
        "tool": NCBI_TOOL,
    }
    if NCBI_EMAIL:
        request_parameters["email"] = NCBI_EMAIL
    if NCBI_API_KEY:
        request_parameters["api_key"] = NCBI_API_KEY
    return f"{base_url}{urllib.parse.urlencode(request_parameters)}"


def _record_uid(record: Any, fallback_uid: str) -> str:
    if not isinstance(record, dict):
        return fallback_uid
    citation = record.get("MedlineCitation", {})
    uid = citation.get("PMID", fallback_uid) if isinstance(citation, dict) else fallback_uid
    if isinstance(uid, dict):
        return str(uid.get("#text", fallback_uid))
    return str(uid)


class _RateLimitedPubMedRetriever(PubMedRetriever):
    def _parse_article(self, uid: str, text_dict: dict[str, Any]) -> dict[str, Any]:
        article = super()._parse_article(uid, text_dict)
        try:
            article_content = text_dict["PubmedArticleSet"]["PubmedArticle"][
                "MedlineCitation"
            ]["Article"]
        except KeyError:
            article_content = text_dict["PubmedArticleSet"]["PubmedBookArticle"][
                "BookDocument"
            ]
        abstract_text = article_content.get("Abstract", {}).get("AbstractText")
        if abstract_text:
            if isinstance(abstract_text, str):
                article["Summary"] = abstract_text
            else:
                abstract_sections = (
                    [abstract_text]
                    if isinstance(abstract_text, dict)
                    else abstract_text
                )
                formatted_sections = []
                for section in abstract_sections:
                    if isinstance(section, str):
                        formatted_sections.append(section)
                        continue
                    label = section.get("@Label", "")
                    nlm_category = section.get("@NlmCategory", "")
                    heading = (
                        f"{label} [{nlm_category}]"
                        if label and nlm_category
                        else label or nlm_category
                    )
                    text = section.get("#text", "")
                    formatted_sections.append(
                        f"{heading}\n{text}" if heading else str(text)
                    )
                article["Summary"] = "\n\n".join(formatted_sections)
        return article

    def lazy_load(self, query: str) -> Iterator[dict[str, Any]]:
        search_url = _ncbi_url(
            self.base_url_esearch,
            {
                "db": "pubmed",
                "term": query[: self.MAX_QUERY_LENGTH],
                "retmode": "json",
                "retmax": str(self.top_k_results),
                "usehistory": "y",
            },
        )
        search_result = json.loads(_request_ncbi(search_url).decode("utf-8"))
        search_data = search_result["esearchresult"]
        uids = [str(uid) for uid in search_data.get("idlist", [])]
        if not uids:
            return

        fetch_url = _ncbi_url(
            self.base_url_efetch,
            {
                "db": "pubmed",
                "retmode": "xml",
                "id": ",".join(uids),
                "webenv": str(search_data.get("webenv", "")),
            },
        )
        parsed = self.parse(_request_ncbi(fetch_url).decode("utf-8"))
        article_set = parsed.get("PubmedArticleSet", {})

        articles = article_set.get("PubmedArticle", [])
        if isinstance(articles, dict):
            articles = [articles]
        for index, article in enumerate(articles):
            fallback_uid = uids[index] if index < len(uids) else ""
            uid = _record_uid(article, fallback_uid)
            yield self._parse_article(
                uid,
                {"PubmedArticleSet": {"PubmedArticle": article}},
            )

        book_articles = article_set.get("PubmedBookArticle", [])
        if isinstance(book_articles, dict):
            book_articles = [book_articles]
        for book_article in book_articles:
            yield self._parse_article(
                "",
                {"PubmedArticleSet": {"PubmedBookArticle": book_article}},
            )


def _document_to_result(document: Any) -> dict[str, Any]:
    metadata = getattr(document, "metadata", {}) or {}
    title = metadata.get("Title") or metadata.get("title") or metadata.get("entry_id") or ""
    pmid = metadata.get("uid") or metadata.get("source") or ""
    abstract = (
        metadata.get("Summary")
        or metadata.get("summary")
        or metadata.get("abstract")
        or getattr(document, "page_content", "")
    )
    url = metadata.get("url") or metadata.get("link") or (
        f"https://pubmed.ncbi.nlm.nih.gov/{pmid}/" if pmid else ""
    )

    return {
        "pmid": str(pmid),
        "title": str(title),
        "abstract": str(abstract),
        "url": str(url),
    }


def _retrieve_documents(retriever: Any, query: str) -> list[Any]:
    if hasattr(retriever, "invoke"):
        return list(retriever.invoke(query))
    return list(retriever.get_relevant_documents(query))


def pubmed_search(case_info: str, max_docs: int = 3) -> dict[str, Any]:
    """
    Search PubMed literature using a focused search query.

    Args:
        case_info: A focused literature query from the provided search_queries.
        max_docs: Maximum number of documents to retrieve. The value is limited to 1-10.
    """
    retriever = _RateLimitedPubMedRetriever(
        top_k_results=max_docs,
        api_key=NCBI_API_KEY,
        email=NCBI_EMAIL,
        max_retry=NCBI_MAX_RETRIES,
        sleep_time=NCBI_RETRY_BASE_SECONDS,
    )
    documents = _retrieve_documents(retriever, case_info)
    results = [_document_to_result(document) for document in documents]
    return {
        "query": case_info,
        "results": [
            result
            for result in results
            if result["pmid"].strip()
            and result["title"].strip()
            and result["abstract"].strip()
            and result["abstract"].strip() != "No abstract available"
        ],
    }


def search_pubmed_queries(search_queries: list[str]) -> list[dict[str, Any]]:
    selected_queries = search_queries
    if not selected_queries:
        return []
    with ThreadPoolExecutor(max_workers=len(selected_queries)) as executor:
        return list(executor.map(pubmed_search, selected_queries))


def build_knowledge_searcher_agent(
    model: str | Model,
    *,
    native_structured_output: bool = True,
) -> Agent:
    return Agent(
        name="Knowledge Searcher Agent",
        model=model,
        instructions=KNOWLEDGE_SEARCHER_INSTRUCTIONS,
        output_type=KnowledgeSearchSelectionResult if native_structured_output else None,
    )
