from __future__ import annotations

from typing import Any

from agents import Agent, function_tool
from langchain_community.retrievers import PubMedRetriever

from config import OPENAI_MODEL


KNOWLEDGE_SEARCHER_INSTRUCTIONS = """
You are a clinical Knowledge search specialist in gastroenterology.

Task:
1. Read the provided search_queries generated by the Gastroenterology Search Planning Agent.
2. Use pubmed_search when external literature search is useful.
3. Search only for literature-relevant evidence, mechanisms, differential diagnosis clues, diagnostic methods, and treatment references.
4. Do not invent papers, titles, authors, URLs, or conclusions.
5. Summarize what the retrieved literature may support, and state when the retrieved results are insufficient.
6. The output is for research assistance only and cannot replace clinical diagnosis or treatment decisions.
7. Write search summaries, extracted evidence, and conclusions in Simplified Chinese.
8. Keep search queries, publication titles, URLs, and quoted source text in their original language.
""".strip()


def _normalize_max_docs(max_docs: int) -> int:
    return max(1, min(max_docs, 10))


def _document_to_result(document: Any) -> dict[str, Any]:
    metadata = getattr(document, "metadata", {}) or {}
    title = metadata.get("Title") or metadata.get("title") or metadata.get("entry_id") or ""
    source = metadata.get("source") or metadata.get("entry_id") or metadata.get("uid") or ""
    url = metadata.get("url") or metadata.get("entry_id") or metadata.get("link") or ""
    published = metadata.get("Published") or metadata.get("published") or metadata.get("pub_date") or ""
    summary = metadata.get("Summary") or metadata.get("summary") or metadata.get("abstract") or ""

    return {
        "title": str(title),
        "source": str(source),
        "url": str(url),
        "published": str(published),
        "summary": str(summary),
        "content": getattr(document, "page_content", ""),
        "metadata": metadata,
    }


def _retrieve_documents(retriever: Any, query: str) -> list[Any]:
    if hasattr(retriever, "invoke"):
        return list(retriever.invoke(query))
    return list(retriever.get_relevant_documents(query))


@function_tool
def pubmed_search(case_info: str, max_docs: int = 5) -> dict[str, Any]:
    """
    Search PubMed literature using a focused search query.

    Args:
        case_info: A focused literature query from the provided search_queries.
        max_docs: Maximum number of documents to retrieve. The value is limited to 1-10.
    """
    normalized_max_docs = _normalize_max_docs(max_docs)
    retriever = PubMedRetriever(load_max_docs=normalized_max_docs)
    documents = _retrieve_documents(retriever, case_info)
    return {
        "source": "pubmed",
        "query": case_info,
        "results": [_document_to_result(document) for document in documents],
    }


def build_knowledge_searcher_agent() -> Agent:
    return Agent(
        name="Knowledge Searcher Agent",
        model=OPENAI_MODEL,
        instructions=KNOWLEDGE_SEARCHER_INSTRUCTIONS,
        tools=[pubmed_search],
    )
