from __future__ import annotations

import json
from collections.abc import Sequence

from agents import Agent

from config import OPENAI_MODEL
from schemas import SearchQueryItem, SimilarCaseRetrievalResult


SIMILAR_CASE_RETRIEVAL_INSTRUCTIONS = """
You are a gastroenterology similar-case retrieval agent.

The input is the search_queries generated by the Gastroenterology Search Planning Agent.

Tasks:
1. Read the intent and query in each search_queries item.
2. Infer the most likely similar-case diagnosis for each query.
3. Output the diagnosis, matching rationale, and confidence for each query.
4. If no real similar-case database or retrieval tool result is available, do not claim that a real case ID, real patient, or real case summary has been retrieved.
5. When no real similar-case database is connected, matched_case_summary must state that the result is inferred only from the query semantics.

Output requirements:
0. All output fields, diagnoses, summaries, rationales, and limitations must be written in English.
1. diagnosis should use a standardized disease name, preferably a gastrointestinal disease name.
2. supporting_reason should be based only on diseases, anatomical sites, symptoms, diagnostic criteria, or differential-diagnosis clues present in the query.
3. limitations must state whether real similar-case database evidence is currently missing.
4. Do not output treatment advice and do not replace clinical diagnosis.
""".strip()


def _search_queries_to_json(search_queries: Sequence[SearchQueryItem]) -> str:
    return json.dumps(
        [query.model_dump() for query in search_queries],
        ensure_ascii=False,
        indent=2,
    )


def build_similar_case_retrieval_prompt(search_queries: Sequence[SearchQueryItem]) -> str:
    return (
        "Search queries from Gastroenterology Search Planning Agent:\n"
        f"{_search_queries_to_json(search_queries)}\n\n"
        "Please infer the corresponding similar-case diagnosis for each query. "
        "Write every output field in English."
    )


def build_similar_case_retrieval_agent() -> Agent:
    return Agent(
        name="Similar Case Retrieval Agent",
        model=OPENAI_MODEL,
        instructions=SIMILAR_CASE_RETRIEVAL_INSTRUCTIONS,
        output_type=SimilarCaseRetrievalResult,
    )
